In [8]:
Objectives:
    - Find out the characteristics of a murderer or a victim
        - Murderer: mental history, history of abuse/trauma, income, relationship status, drug use, age, sex, state, race etc for both, past records... YEAR!!!!!
    - The chances you could be one of those depending on a state or all? (check box lets say you puched someone your prob. goes up)
        - we could run some model like machine learning for classification 

SyntaxError: invalid syntax (<ipython-input-8-c2a44baa112a>, line 1)

In [9]:
Mini objectives:
    - murders by state/town
    - male/female/uknown offenders + state/town/year
    - relationship 
    - figure out victim and perpetrator count if it means 0 is 1 and 1 is 1+1 etc
    - add new data to it 
    - add population data
    - graph value_counts

SyntaxError: invalid syntax (<ipython-input-9-01109cec80a7>, line 1)

In [ ]:
# decision tree, clustering --> NEED target (Homocides/non-homocides)

In [10]:
# importing libraries
import pandas as pd
import numpy as np
import numpy as np

In [11]:
# reading in the file with data
data = pd.read_csv("US HOMOCIDE REPORT.csv",sep=",")

/opt/tljh/user/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [12]:
# 24 columns in total 
# Intiger columns: record ID, Year, incident, Victim Age, Victim Count, Perpertrator Count
# We see an error that PERPERTRATOR AGE IS AN OBJECT
# other columns are object
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 638454 entries, 0 to 638453
Data columns (total 24 columns):
Record ID                638454 non-null int64
Agency Code              638454 non-null object
Agency Name              638454 non-null object
Agency Type              638454 non-null object
City                     638454 non-null object
State                    638454 non-null object
Year                     638454 non-null int64
Month                    638454 non-null object
Incident                 638454 non-null int64
Crime Type               638454 non-null object
Crime Solved             638454 non-null object
Victim Sex               638454 non-null object
Victim Age               638454 non-null int64
Victim Race              638454 non-null object
Victim Ethnicity         638454 non-null object
Perpetrator Sex          638454 non-null object
Perpetrator Age          638454 non-null object
Perpetrator Race         638454 non-null object
Perpetrator Ethnicity    6384

In [13]:
# we investigate
# so part of the numbers are strings so we have to convert the whole column to integers
# but we also see that there is a space which we need to replace
# calculate the ratio 
per_age = data["Perpetrator Age"].unique()
per_age

array([15, 42, 0, 36, 27, 35, 40, 49, 39, 29, 19, 23, 33, 26, 41, 28, 61,
       25, 7, 17, 34, 21, 43, 38, 66, 32, 37, 22, 30, 24, 65, 51, 60, 45,
       64, 18, 20, 44, 73, 62, 69, 52, 16, 90, 56, 47, 57, 31, 46, 14, 55,
       50, 54, 68, 77, 53, 67, 48, 76, 58, 71, 63, 89, 13, 75, 72, 93, 59,
       10, 11, 79, 74, 99, 70, 78, 80, 9, 12, 81, 6, 87, 82, 83, 8, 84,
       85, 86, 5, 3, 1, 88, 95, 4, 91, 92, 96, 94, 2, 98, 97, '22', '52',
       '21', '0', '25', '61', '32', '28', '20', '38', '18', '17', '53',
       '30', '24', '84', '43', '16', '47', '54', '50', '42', '23', '36',
       '35', '60', '27', '19', '14', '57', '63', '81', '31', '58', '51',
       '15', '40', '33', '26', '41', '29', '34', '37', '69', '44', '48',
       '55', '49', '56', '39', '45', '65', '59', '70', '46', '11', '77',
       '67', '76', '85', '72', '13', '89', '74', '71', '64', '62', '3',
       '80', '73', '75', '83', '78', '68', '66', '86', '87', '95', '90',
       '6', '12', '99', '88', '9', '93', '10', 

In [14]:
# WE HAVE about 5000 blanks based on value counts after replacing it with 0 (211,079)
data["Perpetrator Age"].value_counts()

0     211079
20     21158
19     19807
21     18509
18     18477
       ...  
10         1
9          1
1          1
           1
6          1
Name: Perpetrator Age, Length: 191, dtype: int64

In [15]:
# we replace the space with a 0 which could be considered as NA anyways 
# make a copy here of the original so we do not change original data
data1 = data.copy()

In [16]:
# appearently we have to convert stuff into strings first and then to integers (don't ask me)
data1['Perpetrator Age'] = data1['Perpetrator Age'].replace(" ", 0)

In [17]:
data1["Perpetrator Age"]

0         15
1         42
2          0
3         42
4          0
          ..
638449     0
638450    57
638451    22
638452    31
638453    24
Name: Perpetrator Age, Length: 638454, dtype: object

### Have to replace 0s and all ages under 13/14 (youngest murderer in US is 13

In [18]:
data1['Perpetrator Age'] = data1['Perpetrator Age'].astype(str).astype(int)
# this didnt work
#data['Perpetrator Age'] = pd.to_numeric(data['Perpetrator Age'], errors="coerce").head()

In [19]:
# converting 0s into the mean
# cuz other values are there, offense was made just record of age isnt
# appearently we have to convert stuff into strings first and then to integers (don't ask me)
data1['Perpetrator Age']

0         15
1         42
2          0
3         42
4          0
          ..
638449     0
638450    57
638451    22
638452    31
638453    24
Name: Perpetrator Age, Length: 638454, dtype: int64

In [20]:
# we see that our little problem was solved
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 638454 entries, 0 to 638453
Data columns (total 24 columns):
Record ID                638454 non-null int64
Agency Code              638454 non-null object
Agency Name              638454 non-null object
Agency Type              638454 non-null object
City                     638454 non-null object
State                    638454 non-null object
Year                     638454 non-null int64
Month                    638454 non-null object
Incident                 638454 non-null int64
Crime Type               638454 non-null object
Crime Solved             638454 non-null object
Victim Sex               638454 non-null object
Victim Age               638454 non-null int64
Victim Race              638454 non-null object
Victim Ethnicity         638454 non-null object
Perpetrator Sex          638454 non-null object
Perpetrator Age          638454 non-null int64
Perpetrator Race         638454 non-null object
Perpetrator Ethnicity    63845

In [21]:
# double check 
data1['Perpetrator Age'].unique()

array([15, 42,  0, 36, 27, 35, 40, 49, 39, 29, 19, 23, 33, 26, 41, 28, 61,
       25,  7, 17, 34, 21, 43, 38, 66, 32, 37, 22, 30, 24, 65, 51, 60, 45,
       64, 18, 20, 44, 73, 62, 69, 52, 16, 90, 56, 47, 57, 31, 46, 14, 55,
       50, 54, 68, 77, 53, 67, 48, 76, 58, 71, 63, 89, 13, 75, 72, 93, 59,
       10, 11, 79, 74, 99, 70, 78, 80,  9, 12, 81,  6, 87, 82, 83,  8, 84,
       85, 86,  5,  3,  1, 88, 95,  4, 91, 92, 96, 94,  2, 98, 97])

In [22]:
# ok so about 1/3 of the perpetrator age is 0 need to modify or subset (mean/median/most freq/drop)
# from 0 - 99 
# Expecting that most values will be between 18-40
perp_age = data1["Perpetrator Age"].value_counts()
perp_age

0     216328
20     21625
19     20250
21     18983
18     18834
       ...  
95         9
98         7
96         7
2          6
97         3
Name: Perpetrator Age, Length: 100, dtype: int64

In [23]:
# the 0 values skews our results so i am expecting the mean to be higher than 20 when adjusted
# this is explain by high standard devition and bottom 25% which is 0 (1/3 values are 0)
data1["Perpetrator Age"].describe()

count    638454.000000
mean         20.322665
std          17.886846
min           0.000000
25%           0.000000
50%          21.000000
75%          31.000000
max          99.000000
Name: Perpetrator Age, dtype: float64

### Transforming Perpetrator Age <=13 to the mean and stdev

In [24]:
# it gets for every column but ut doesnt matter
# we are looking for count of perpetrator age that is equal or below 13 = 218668
# from the df count the following condition based on the series less or equal to 13
data1[data1['Perpetrator Age'] <= 13].count()

Record ID                218668
Agency Code              218668
Agency Name              218668
Agency Type              218668
City                     218668
State                    218668
Year                     218668
Month                    218668
Incident                 218668
Crime Type               218668
Crime Solved             218668
Victim Sex               218668
Victim Age               218668
Victim Race              218668
Victim Ethnicity         218668
Perpetrator Sex          218668
Perpetrator Age          218668
Perpetrator Race         218668
Perpetrator Ethnicity    218668
Relationship             218668
Weapon                   218668
Victim Count             218668
Perpetrator Count        218668
Record Source            218668
dtype: int64

In [25]:
# find a mean without zeros
#if data1["Perpetrator Age"]  
nonzero_mean = data1["Perpetrator Age"][data1["Perpetrator Age"] >= 13 ].mean()
nonzero_mean

30.798633863552666

In [26]:
# find standard deviation without zeros
non_stdev = data1["Perpetrator Age"][data1["Perpetrator Age"] >= 13 ].std()
non_stdev

12.76506550523528

In [27]:
# https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.truncnorm.html

In [28]:
# applying the mean of age with stdev randomly to zero values 
# we need to generate a random whole numbers list for all zeros --> 216,328 

In [29]:
# so between age 13 and 99
# mean is 31, stdev is 13 (have to round up to be whole number)
import scipy.stats as stats

# shape parameters
a, b = 13, 99 
# mean and standard deviation
mu, sigma = 31, 13

# A truncated normal continuous random variable
# truncated normal distribution is the probability distribution derived from that of a normally 
# distributed random variable by bounding the random variable from either below or above (or both). 
# probability density function is the probability of something happening within certain range / upper bound 
# restricting normal distribution between an interval 
# a - mu --> 13 - 31 range/13, 99-31/13, loc = location parameter (mean), scale parameter = scale (sigma) --> so stdev will move up and down based on the mean
dist = stats.truncnorm((a - mu) / sigma, (b - mu) / sigma, loc=mu, scale=sigma)

# generate 218668 random numbers based dist conditions 
values = dist.rvs(218668)

### Checking results

In [30]:
# we got our np.array of 218668 numbers 
# mean is not exactly the same but it changes with each new generation 
# count stays the same 
# the result is acceptable 
# now we have to replace it with values that are <= 13 (perpetrator age)

In [31]:
values

array([43.60612931, 36.03880478, 15.52898376, ..., 30.79335381,
       26.27269131, 26.19162766])

In [32]:
# checking the results

In [33]:
values.mean()

33.149992440604656

In [34]:
values.std()

11.166249598916291

In [35]:
np.count_nonzero(values)

218668

In [36]:
# making it a series for plug in
new_perp_age = pd.Series(values)
type(new_perp_age)
#new_perp_age

pandas.core.series.Series

### Make the new_perp_age into whole numbers

In [37]:
data1["Perpetrator Age"] <= 13

0         False
1         False
2          True
3         False
4          True
          ...  
638449     True
638450    False
638451    False
638452    False
638453    False
Name: Perpetrator Age, Length: 638454, dtype: bool

In [38]:
data1["Perpetrator Age"].iloc[0:]

0         15
1         42
2          0
3         42
4          0
          ..
638449     0
638450    57
638451    22
638452    31
638453    24
Name: Perpetrator Age, Length: 638454, dtype: int64

### Replacing perpetrator age

In [39]:
# just subset the whole thing based on condition and then just choose that column
data2 = data1.copy()
perp_wrong_age = data2[data2["Perpetrator Age"] <= 13]
#more_scientists_df[more_scientists_df.Age > more_scientists_df.Age.mean()]

In [40]:
# selecting col to get rid of blank values 
s = perp_wrong_age["Perpetrator Age"]

In [41]:
# selected the series index
perp_index = s.index



In [42]:
new_perp_age.reindex(index = s)

Perpetrator Age
0    43.606129
0    43.606129
0    43.606129
0    43.606129
0    43.606129
       ...    
0    43.606129
0    43.606129
0    43.606129
0    43.606129
0    43.606129
Length: 218668, dtype: float64

In [43]:
# update values doesnt work for all 
# doesnt update cuz it has different indexes but if I reset the index then how can I put it back in a proper place
# so you subset some data based on condition 
perp_wrong_age["Perpetrator Age"].update(new_perp_age, index = s)

TypeError: update() got an unexpected keyword argument 'index'

In [ ]:
#perp_wrong_age

In [ ]:
# select perp age col and put new values in (but how would it be analytical?)
perp_wrong_age["Perpetrator Age"] = perp_wrong_age[new_perp_age]

In [ ]:
# sort and then subset only <=13, replace it with new vals and then plug it back in 
perp_age_series = data1["Perpetrator Age"] <= 13

In [ ]:
# select only those items that satisfy the condition 

In [ ]:
if perp_age_series == "True":
    print(perp_age_series)

In [ ]:
l = pd.DataFrame()
for i in new_perp_age:
    if data1["Perpetrator Age"].iloc[2] <= 13:
        data1["Perpetrator Age"].iloc[2].replace(data1["Perpetrator Age"].iloc[2],i)
data1["Perpetrator Age"].iloc[2]

In [ ]:
data1.loc[data1["Perpetrator Age"] <= 13] = new_perp_age

In [ ]:
data1

In [44]:
# Original data --> no nulls in df and no na's
data.isnull().sum()

Record ID                0
Agency Code              0
Agency Name              0
Agency Type              0
City                     0
State                    0
Year                     0
Month                    0
Incident                 0
Crime Type               0
Crime Solved             0
Victim Sex               0
Victim Age               0
Victim Race              0
Victim Ethnicity         0
Perpetrator Sex          0
Perpetrator Age          0
Perpetrator Race         0
Perpetrator Ethnicity    0
Relationship             0
Weapon                   0
Victim Count             0
Perpetrator Count        0
Record Source            0
dtype: int64

In [45]:
data.isna().sum()

Record ID                0
Agency Code              0
Agency Name              0
Agency Type              0
City                     0
State                    0
Year                     0
Month                    0
Incident                 0
Crime Type               0
Crime Solved             0
Victim Sex               0
Victim Age               0
Victim Race              0
Victim Ethnicity         0
Perpetrator Sex          0
Perpetrator Age          0
Perpetrator Race         0
Perpetrator Ethnicity    0
Relationship             0
Weapon                   0
Victim Count             0
Perpetrator Count        0
Record Source            0
dtype: int64

In [46]:
# we will familiarize ourselves with the values of columns now to see what to expect
data1['Agency Name'].unique()

array(['Anchorage', 'Juneau', 'Nome', ..., 'Sp: Hundred',
       'Sheridan County', 'Sublette County'], dtype=object)

In [47]:
# New York agency has the most work (about 5-6% of data), LA, Chicago 
agency_values = data1["Agency Name"].value_counts()
agency_values

New York           38416
Los Angeles        29007
Chicago            21331
Detroit            17206
Houston            13046
                   ...  
Southside Place        1
Caro                   1
El Lago                1
Mora                   1
Ontario County         1
Name: Agency Name, Length: 9216, dtype: int64

In [48]:
# over 9000 different agencies, New York is top 
agency_values.describe()

count     9216.000000
mean        69.276693
std        683.511828
min          1.000000
25%          2.000000
50%          7.000000
75%         23.000000
max      38416.000000
Name: Agency Name, dtype: float64

In [49]:
data1['Agency Type'].unique()

array(['Municipal Police', 'County Police', 'State Police', 'Sheriff',
       'Special Police', 'Regional Police', 'Tribal Police'], dtype=object)

In [50]:
# about 85% of cases are handled by the municipal police
agency_type = data1["Agency Type"].value_counts()
agency_type

Municipal Police    493026
Sheriff             105322
County Police        22693
State Police         14235
Special Police        2889
Regional Police        235
Tribal Police           54
Name: Agency Type, dtype: int64

In [51]:
# 7 different groups of organizations that handle homocides
# on average the handle 91,000 each with a big standard deviation meaning positive skew (municipal polica)
# which explains the quartiles
agency_type.describe()

count         7.000000
mean      91207.714286
std      181043.936785
min          54.000000
25%        1562.000000
50%       14235.000000
75%       64007.500000
max      493026.000000
Name: Agency Type, dtype: float64

In [52]:
data1['City'].unique()

array(['Anchorage', 'Juneau', 'Nome', ..., 'Rooks', 'McCone', 'Antelope'],
      dtype=object)

In [53]:
# how does NY police has most to handle while LA city has the most here (different departments?)
# are police departments more split up than NY?
# how does such small towns have to many acticity?? Probably wrong might have to frop entire column
city = data1["City"].value_counts()
city

Los Angeles    44511
New York       38431
Cook           22383
Wayne          19904
Harris         16331
               ...  
Piute              1
Big Stone          1
Bowman             1
Carlisle           1
Divide             1
Name: City, Length: 1782, dtype: int64

In [54]:
# 1800 diff cities, incidinces per city about 350
city.describe()

count     1782.000000
mean       358.279461
std       1843.878372
min          1.000000
25%         15.000000
50%         41.000000
75%        154.000000
max      44511.000000
Name: City, dtype: float64

In [55]:
# we see where most stuff happens we dont know if its bad yet but probably is 
# Top: CA, TX, NY hold about 10%, 5%, 4%
values_per_state = data1['State'].value_counts()
values_per_state

California              99783
Texas                   62095
New York                49268
Florida                 37164
Michigan                28448
Illinois                25871
Pennsylvania            24236
Georgia                 21088
North Carolina          20390
Louisiana               19629
Ohio                    19158
Maryland                17312
Virginia                15520
Tennessee               14930
Missouri                14832
New Jersey              14132
Arizona                 12871
South Carolina          11698
Indiana                 11463
Alabama                 11376
Oklahoma                 8809
Washington               7815
District of Columbia     7115
Arkansas                 6947
Colorado                 6593
Kentucky                 6554
Mississippi              6546
Wisconsin                6191
Massachusetts            6036
Nevada                   5553
Connecticut              4896
New Mexico               4272
Oregon                   4217
Minnesota 

In [56]:
# more than 50 states!!
count_states = values_per_state.count()
count_states

51

In [57]:
# I guess there is no duplicates but one doesnt belong 
# OK District of Columbia which is not a state ? should we drop it? it has 7000+ observations, so nah
duplicate_state = values_per_state.duplicated()
duplicate_state

California              False
Texas                   False
New York                False
Florida                 False
Michigan                False
Illinois                False
Pennsylvania            False
Georgia                 False
North Carolina          False
Louisiana               False
Ohio                    False
Maryland                False
Virginia                False
Tennessee               False
Missouri                False
New Jersey              False
Arizona                 False
South Carolina          False
Indiana                 False
Alabama                 False
Oklahoma                False
Washington              False
District of Columbia    False
Arkansas                False
Colorado                False
Kentucky                False
Mississippi             False
Wisconsin               False
Massachusetts           False
Nevada                  False
Connecticut             False
New Mexico              False
Oregon                  False
Minnesota 

In [58]:
# ok "51" states, about 12500 incidences per state, huge colatility probably due to big cities
# meadian is 6500 so yes skew to the left 
values_per_state.describe()

count       51.000000
mean     12518.705882
std      17686.520705
min        308.000000
25%       1683.000000
50%       6554.000000
75%      15225.000000
max      99783.000000
Name: State, dtype: float64

In [59]:
# ok so data from 1980 to 2014
# probably all data is not available or every year though
year = data1["Year"].unique()
year

array([1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990,
       1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014])

In [60]:
years_count = data1["Year"].value_counts()
years_count
# Top 3: 1993, 1992, 1994

1993    24335
1992    23793
1994    23246
1980    23092
1991    22657
1990    21246
1981    21208
1995    21179
1982    20544
1986    20125
1989    19868
1983    19653
1996    18969
1987    18783
1988    18779
1985    18386
1984    18093
1997    17794
2007    17303
2006    17275
2005    16836
2003    16512
2002    16268
2004    16233
1998    16061
2009    15840
2001    15803
2008    15595
2010    15121
2012    15033
2011    14756
2000    14671
1999    14621
2013    14445
2014    14331
Name: Year, dtype: int64

In [61]:
# data over 35 years, about 18,000 incidences a year 
# distribution looks quite normal 
years_count.describe()

count       35.000000
mean     18241.542857
std       2986.446653
min      14331.000000
25%      15821.500000
50%      17794.000000
75%      20334.500000
max      24335.000000
Name: Year, dtype: float64

In [62]:
# 12 months looks in order 
unique_month = data1["Month"].unique()
unique_month

array(['January', 'March', 'April', 'May', 'June', 'July', 'August',
       'December', 'November', 'February', 'October', 'September'],
      dtype=object)

In [63]:
# top 3: July, August, December --> the extremes interesting
# also very equal distribution over months as in years
# Hypothesis: more encounters in summer due to the head (people out more?)
month_val = data1["Month"].value_counts()
month_val

July         58696
August       58072
December     55187
September    54117
June         53662
October      53650
May          53394
January      52928
March        51444
April        51209
November     50016
February     46079
Name: Month, dtype: int64

In [64]:
# this supports the normal distribution
month_val.describe()

count       12.000000
mean     53204.500000
std       3399.904985
min      46079.000000
25%      51385.250000
50%      53522.000000
75%      54384.500000
max      58696.000000
Name: Month, dtype: float64

In [65]:
data1["Incident"].max()

999

In [66]:
# from 0 to 999 (zero might be an error) --> have to check what 0 means
types_incident = data1["Incident"].unique()
types_incident

array([  1,   2,   3,   4,  41,   5,   6,   7,   8,   9,  10,  11,  33,
        12,  17,  13,  14,  15,  16,  18,  21,  19,  20,  22,  23,  60,
        28,  59,  29,  24,  66,  54,  49,  77,  40,  82,  37,  86,  31,
        53,  90,  25,  26,  27,  30,  32,  34,  35,  36,  38,  39,  42,
        43,  44,  45,  46,  47,  48,  50,  51,  52,  55,  56,  57,  58,
        61,  62,  63,  64,  65,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  78,  79,  80,  81,  83,  84,  85,  87,  88,  89,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 137, 126, 134, 151, 125, 205, 124,
       127, 128, 129, 130, 131, 132, 133, 135, 136, 138, 139, 140, 141,
       142, 143, 144, 145, 146, 147, 148, 149, 150, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [67]:
# so many have enough after 1 time
# more than 1/3 is 1
# what does incident really mean?
# 0 is inly 16 times but what is it?
# FIND OUT WHAT IT MEANS 
# FIND Index of extreme values 
inc_val = data1["Incident"].value_counts()
inc_val

1      265528
2       71779
3       39236
4       27113
5       20658
        ...  
784        16
783        16
782        16
781        16
0          16
Name: Incident, Length: 1000, dtype: int64

In [68]:
# 1000 diff incidences?, 630 on average, huge deviation to left skew (big cities)
inc_val.describe()

count      1000.000000
mean        638.454000
std        8900.322851
min          16.000000
25%          16.000000
50%          17.000000
75%          19.000000
max      265528.000000
Name: Incident, dtype: float64

In [69]:
# 2 possible answers
# diffine it 
crime_type = data1["Crime Type"].unique()
crime_type

array(['Murder or Manslaughter', 'Manslaughter by Negligence'],
      dtype=object)

In [70]:
# so most people kill with intent (unless framed) (about 95%)
cr_val = data1["Crime Type"].value_counts()
cr_val

Murder or Manslaughter        629338
Manslaughter by Negligence      9116
Name: Crime Type, dtype: int64

In [71]:
cr_val.describe()

count         2.000000
mean     319227.000000
std      438563.182041
min        9116.000000
25%      164171.500000
50%      319227.000000
75%      474282.500000
max      629338.000000
Name: Crime Type, dtype: float64

In [72]:
crime_solved = data1["Crime Solved"].unique()
crime_solved

array(['Yes', 'No'], dtype=object)

In [73]:
# more than half crimes were solved
solve_val = data1["Crime Solved"].value_counts()
solve_val

Yes    448172
No     190282
Name: Crime Solved, dtype: int64

In [74]:
solve_val.describe()

count         2.0000
mean     319227.0000
std      182355.7678
min      190282.0000
25%      254754.5000
50%      319227.0000
75%      383699.5000
max      448172.0000
Name: Crime Solved, dtype: float64

In [75]:
# 3 posible options
vic_sex = data1["Victim Sex"].unique()
vic_sex

array(['Male', 'Female', 'Unknown'], dtype=object)

In [76]:
# Like 3/4 males are victims hmm...
sex_vic = data1["Victim Sex"].value_counts()
sex_vic

Male       494125
Female     143345
Unknown       984
Name: Victim Sex, dtype: int64

In [77]:
sex_vic.describe()

count         3.00000
mean     212818.00000
std      253804.81628
min         984.00000
25%       72164.50000
50%      143345.00000
75%      318735.00000
max      494125.00000
Name: Victim Sex, dtype: float64

In [78]:
# from 0-998 --> ERROR!!!
# REMOVE 998 how many times does 998 appear? and how many times 0?
vic_age = data1["Victim Age"].unique()
vic_age

array([ 14,  43,  30,  42,  99,  32,  38,  36,  20,  48,  31,  16,  33,
        27,  21,  60,  40,  18,   8,  25,  24,  46,  23,  22,  45,  26,
        58,  17,  29,  41,  68,  13,  35,  44,  54,  37,  51,  90,  50,
        52,  61,  63,  19,  28,  70,  72,  74,  53,  57,  76,  79,  69,
        34,  66,  55,  67,  65,  47,   1,  49,  62,  75,  56,  59,  78,
        39,  15,   0,  71,  77,   2,   4,  64,  82,  85,   6,   5,   7,
         9,  84,  10,  86,  11,  73,  83, 998,  81,  87,  80,   3,  12,
        94,  93,  92,  89,  97,  88,  91,  95,  98,  96])

In [79]:
# most victims age in the 20s
vic_age_count = data1["Victim Age"].value_counts()
vic_age_count

22    23049
20    23031
25    22939
21    22796
23    22438
      ...  
94      116
95       82
97       39
96       37
98       33
Name: Victim Age, Length: 101, dtype: int64

In [80]:
# women live longer
vic_age_count.describe()

count      101.000000
mean      6321.326733
std       6989.412844
min         33.000000
25%       1067.000000
50%       3171.000000
75%       9594.000000
max      23049.000000
Name: Victim Age, dtype: float64

In [81]:
# 4 options
victim_race = data1["Victim Race"].unique()
victim_race

array(['Native American/Alaska Native', 'White', 'Black', 'Unknown',
       'Asian/Pacific Islander'], dtype=object)

In [82]:
# most vics are white, black about 48%, 47% 
vic_race = data1["Victim Race"].value_counts()
vic_race

White                            317422
Black                            299899
Asian/Pacific Islander             9890
Unknown                            6676
Native American/Alaska Native      4567
Name: Victim Race, dtype: int64

In [83]:
# 3 options
vic_eth = data1["Victim Ethnicity"].unique()
vic_eth

array(['Unknown', 'Not Hispanic', 'Hispanic'], dtype=object)

In [84]:
# most are uknown 8missing data?, then about 27% are either white, black, asian
vi_eth = data1["Victim Ethnicity"].value_counts()
vi_eth

Unknown         368303
Not Hispanic    197499
Hispanic         72652
Name: Victim Ethnicity, dtype: int64

In [85]:
# from 0-99
perp_age = data1["Perpetrator Age"].unique()
perp_age

array([15, 42,  0, 36, 27, 35, 40, 49, 39, 29, 19, 23, 33, 26, 41, 28, 61,
       25,  7, 17, 34, 21, 43, 38, 66, 32, 37, 22, 30, 24, 65, 51, 60, 45,
       64, 18, 20, 44, 73, 62, 69, 52, 16, 90, 56, 47, 57, 31, 46, 14, 55,
       50, 54, 68, 77, 53, 67, 48, 76, 58, 71, 63, 89, 13, 75, 72, 93, 59,
       10, 11, 79, 74, 99, 70, 78, 80,  9, 12, 81,  6, 87, 82, 83,  8, 84,
       85, 86,  5,  3,  1, 88, 95,  4, 91, 92, 96, 94,  2, 98, 97])

In [86]:
# 0 must be an error the way we handled it above saying that space = 0
# others = 20,19, 21 --> many angry young man
perpr_age = data1["Perpetrator Age"].value_counts()
perpr_age

0     216328
20     21625
19     20250
21     18983
18     18834
       ...  
95         9
98         7
96         7
2          6
97         3
Name: Perpetrator Age, Length: 100, dtype: int64

In [87]:
per_sex = data1["Perpetrator Sex"].unique()
per_sex

array(['Male', 'Unknown', 'Female'], dtype=object)

In [88]:
# mostly males again?? about 60%
perp_age = data1["Perpetrator Sex"].value_counts()
perp_age

Male       399541
Unknown    190365
Female      48548
Name: Perpetrator Sex, dtype: int64

In [89]:
# prob missing data therfore uknown 
perp_eth = data1["Perpetrator Ethnicity"].value_counts()
perp_eth

Unknown         446410
Not Hispanic    145172
Hispanic         46872
Name: Perpetrator Ethnicity, dtype: int64

In [90]:
# here we go again. but considering there is more white people the difference isnt big with others 30% 30% 30%
data["Perpetrator Race"].value_counts()

White                            218243
Black                            214516
Unknown                          196047
Asian/Pacific Islander             6046
Native American/Alaska Native      3602
Name: Perpetrator Race, dtype: int64

In [91]:
# mainly killed by uknown 27% of a time(prob not entered in system), aquitance, then stranger
# what does this mean is the "wife" the killer or the victim
# victim 
# does it relate to solved or unsolved crimes?
relat = data1["Relationship"].value_counts()
relat

Unknown                 273013
Acquaintance            126018
Stranger                 96593
Wife                     23187
Friend                   21945
Girlfriend               16465
Son                       9904
Family                    9535
Husband                   8803
Daughter                  7539
Boyfriend                 7302
Neighbor                  6294
Brother                   5514
Father                    4361
Mother                    4248
In-Law                    3637
Common-Law Wife           2477
Ex-Wife                   1973
Common-Law Husband        1954
Boyfriend/Girlfriend      1383
Stepfather                1360
Sister                    1292
Stepson                   1170
Stepdaughter               754
Ex-Husband                 629
Employer                   509
Employee                   384
Stepmother                 211
Name: Relationship, dtype: int64

In [92]:
# 28 diff relationships, left skew
relat.describe()

count        28.000000
mean      22801.928571
std       56764.034682
min         211.000000
25%        1343.000000
50%        4304.500000
75%        9627.250000
max      273013.000000
Name: Relationship, dtype: float64

In [93]:
# half die with a gun, 8% by knife
# massshootings?
# uknown solved or unsolved?
weapond = data1["Weapon"].value_counts()
weapond

Handgun          317484
Knife             94962
Blunt Object      67337
Firearm           46980
Unknown           33192
Shotgun           30722
Rifle             23347
Strangulation      8110
Fire               6173
Suffocation        3968
Gun                2206
Drugs              1588
Drowning           1204
Explosives          537
Poison              454
Fall                190
Name: Weapon, dtype: int64

In [94]:
# left skew, 16 vays to die
weapond.describe()

count        16.000000
mean      39903.375000
std       79077.353807
min         190.000000
25%        1492.000000
50%        7141.500000
75%       36639.000000
max      317484.000000
Name: Weapon, dtype: float64

In [95]:
# WHAT does 0 mean ?? as 1?
# still check
# if 0 +1 is correct 
# no inputs or uknowns 
perp_count = data1["Perpetrator Count"].value_counts()
perp_count

0     558838
1      54745
2      15777
3       6531
4       1489
5        592
6        207
7        129
9         52
8         52
10        42
Name: Perpetrator Count, dtype: int64

In [96]:
perp_count.describe()

count        11.000000
mean      58041.272727
std      166893.512297
min          42.000000
25%          90.500000
50%         592.000000
75%       11154.000000
max      558838.000000
Name: Perpetrator Count, dtype: float64

In [97]:
vic_count = data1["Victim Count"].value_counts()
vic_count

0     586059
1      38750
2       8156
3       2847
4       1084
5        510
9        290
6        286
7        168
10       160
8        144
Name: Victim Count, dtype: int64

In [98]:
vic_count.describe()

count        11.000000
mean      58041.272727
std      175495.393843
min         144.000000
25%         227.000000
50%         510.000000
75%        5501.500000
max      586059.000000
Name: Victim Count, dtype: float64

In [99]:
rec_source = data["Record Source"].value_counts()
rec_source

FBI     616647
FOIA     21807
Name: Record Source, dtype: int64

In [100]:
# Deleting

In [103]:
del_0age = data1.drop(data1["Perpetrator Age"] ==0)
del_0age

KeyError: '[False False  True ... False False False] not found in axis'

In [ ]:
# Saving clean data
#data.to_csv("US Homicidev2.csv")